# Using SGD Classifier

In [ ]:
data = pd.read_csv('train_mosaic.csv')

In [2]:
import pandas as pd
import numpy as np

In [4]:
data

Destination_Port  Flow_Duration  Total_Fwd_Packets  \
0                     80      101168794                 20   
1                  60711             58                  1   
2                     53          31146                  4   
3                     80         254704                  3   
4                    443       11932077                 12   
...                  ...            ...                ...   
809356                80       68156881                 10   
809357                80         173608                  7   
809358                80       61923754                  7   
809359                53            744                  2   
809360                80         196947                 10   

        Total_Backward_Packets  Total_Length_of_Fwd_Packets  \
0                            1                          969   
1                            1                            0   
2                            2                          148   
3                            4                          429   
4                           16                         5030   
...                        ...                          ...   
809356                       1                          233   
809357                       1                          344   
809358                       1                          210   
809359                       2                           88   
809360                       1                          305   

        Total_Length_of_Bwd_Packets  Fwd_Packet_Length_Max  \
0                                 0                    353   
1                                 0                      0   
2                               244                     37   
3                               389                    423   
4                             15703                   1525   
...                             ...                    ...   
809356                            0                    168   
809357                            0                    344   
809358                            0                    168   
809359                          200                     44   
809360                            0                    305   

        Fwd_Packet_Length_Min  Fwd_Packet_Length_Mean  Fwd_Packet_Length_Std  \
0                           0               48.450000             119.083551   
1                           0                0.000000               0.000000   
2                          37               37.000000               0.000000   
3                           0              143.000000             242.505670   
4                           0              419.166667             644.896586   
...                       ...                     ...                    ...   
809356                      0               23.300000              51.337770   
809357                      0               49.142857             130.019779   
809358                      0               30.000000              61.326992   
809359                     44               44.000000               0.000000   
809360                      0               30.500000              96.449469   

        ...  min_seg_size_forward  Active_Mean    Active_Std  Active_Max  \
0       ...                   0.0     739228.5  7.431035e+05   1264682.0   
1       ...                  32.0          0.0  0.000000e+00         0.0   
2       ...                  20.0          0.0  0.000000e+00         0.0   
3       ...                  20.0          0.0  0.000000e+00         0.0   
4       ...                  20.0          0.0  0.000000e+00         0.0   
...     ...                   ...          ...           ...         ...   
809356  ...                   0.0     165265.0  1.529792e+05    306895.0   
809357  ...                   0.0          0.0  0.000000e+00         0.0   
809358  ...                   0.0    1273143.0  1.798484e+06   2544863.0   
809359  ...                  20.0       

In [5]:
data.describe()

Destination_Port  Flow_Duration  Total_Fwd_Packets  \
count     809361.000000   8.093610e+05      809361.000000   
mean        4904.991302   2.504842e+07           9.073800   
std        15382.903368   3.554362e+07         542.751484   
min            0.000000  -1.000000e+00           1.000000   
25%           80.000000   3.093200e+04           2.000000   
50%           80.000000   7.043440e+05           6.000000   
75%           80.000000   5.149215e+07           9.000000   
max        65535.000000   1.200000e+08      219759.000000   

       Total_Backward_Packets  Total_Length_of_Fwd_Packets  \
count           809361.000000                 8.093610e+05   
mean                 5.318512                 4.659948e+02   
std                719.218470                 3.782515e+03   
min                  0.000000                 0.000000e+00   
25%                  1.000000                 5.800000e+01   
50%                  1.000000                 2.320000e+02   
75%                  2.000000                 4.150000e+02   
max             291922.000000                 1.323378e+06   

       Total_Length_of_Bwd_Packets  Fwd_Packet_Length_Max  \
count                 8.093610e+05          809361.000000   
mean                  7.041397e+03             229.735331   
std                   1.623593e+06             314.052604   
min                   0.000000e+00               0.000000   
25%                   0.000000e+00              37.000000   
50%                   0.000000e+00             168.000000   
75%                   1.180000e+02             347.000000   
max                   6.554530e+08           23360.000000   

       Fwd_Packet_Length_Min  Fwd_Packet_Length_Mean  Fwd_Packet_Length_Std  \
count          809361.000000           809361.000000          809361.000000   
mean                9.306948               48.846569              81.858579   
std                26.341044               65.069803             107.997283   
min                 0.000000                0.000000               0.000000   
25%                 0.000000               25.777778               0.000000   
50%                 0.000000               41.000000              61.354163   
75%                 6.000000               58.416667             130.878198   
max              1472.000000             3909.410256            5087.863270   

       ...  act_data_pkt_fwd  min_seg_size_forward   Active_Mean  \
count  ...     809361.000000          8.093610e+05  8.093610e+05   
mean   ...          4.327992         -1.749905e+03  3.146043e+05   
std    ...        522.596651          3.844457e+05  9.096841e+05   
min    ...          0.000000         -8.388531e+07  0.000000e+00   
25%    ...          1.000000          0.000000e+00  0.000000e+00   
50%    ...          1.000000          0.000000e+00  0.000000e+00   
75%    ...          3.000000          2.000000e+01  1.615060e+05   
max    ...     213557.000000          1.260000e+02  1.016597e+08   

         Active_Std    Active_Max    Active_Min     Idle_Mean      Idle_Std  \
count  8.093610e+05  8.093610e+05  8.093610e+05  8.093610e+05  8.093610e+05   
mean   1.738503e+05  4.680256e+05  1.929457e+05  1.373910e+07  2.446688e+06   
std    6.192143e+05  1.300849e+06  7.747840e+05  2.433428e+07  7.024856e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  2.066600e+05  3.592500e+04  1.930000e+07  0.000000e+00   
max    6.434950e+07  1.016597e+08  1.016597e+08  1.200000e+08  7.670000e+07   

           Idle_Max      Idle_Min  
count  8.093610e+05  8.093610e+05  
mean   1.585056e+07  1.179622e+07  
std    2.627564e+07  2.363940e+07  
min    0.000000e+00  0.000000e+00  
25%    0.000000e+00  0.000000e+00  
50%    0.000000e+00  0.000000e+00  
75%    2.465353e+07  1.239779e+07  
max    1.200000e+08  1.

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 809361 entries, 0 to 809360
Data columns (total 78 columns):
Destination_Port               809361 non-null int64
Flow_Duration                  809361 non-null int64
Total_Fwd_Packets              809361 non-null int64
Total_Backward_Packets         809361 non-null int64
Total_Length_of_Fwd_Packets    809361 non-null int64
Total_Length_of_Bwd_Packets    809361 non-null int64
Fwd_Packet_Length_Max          809361 non-null int64
Fwd_Packet_Length_Min          809361 non-null int64
Fwd_Packet_Length_Mean         809361 non-null float64
Fwd_Packet_Length_Std          809361 non-null float64
Bwd_Packet_Length_Max          809361 non-null int64
Bwd_Packet_Length_Min          809361 non-null int64
Bwd_Packet_Length_Mean         809361 non-null float64
Bwd_Packet_Length_Std          809361 non-null float64
Flow_Bytes_Sec                 809361 non-null float64
Flow_Packets_Sec               809361 non-null float64
Flow_IAT_Mean                

In [11]:
from sklearn.linear_model import SGDClassifier
X=data.iloc[:,:77]
X

Destination_Port  Flow_Duration  Total_Fwd_Packets  \
0                     80      101168794                 20   
1                  60711             58                  1   
2                     53          31146                  4   
3                     80         254704                  3   
4                    443       11932077                 12   
...                  ...            ...                ...   
809356                80       68156881                 10   
809357                80         173608                  7   
809358                80       61923754                  7   
809359                53            744                  2   
809360                80         196947                 10   

        Total_Backward_Packets  Total_Length_of_Fwd_Packets  \
0                            1                          969   
1                            1                            0   
2                            2                          148   
3                            4                          429   
4                           16                         5030   
...                        ...                          ...   
809356                       1                          233   
809357                       1                          344   
809358                       1                          210   
809359                       2                           88   
809360                       1                          305   

        Total_Length_of_Bwd_Packets  Fwd_Packet_Length_Max  \
0                                 0                    353   
1                                 0                      0   
2                               244                     37   
3                               389                    423   
4                             15703                   1525   
...                             ...                    ...   
809356                            0                    168   
809357                            0                    344   
809358                            0                    168   
809359                          200                     44   
809360                            0                    305   

        Fwd_Packet_Length_Min  Fwd_Packet_Length_Mean  Fwd_Packet_Length_Std  \
0                           0               48.450000             119.083551   
1                           0                0.000000               0.000000   
2                          37               37.000000               0.000000   
3                           0              143.000000             242.505670   
4                           0              419.166667             644.896586   
...                       ...                     ...                    ...   
809356                      0               23.300000              51.337770   
809357                      0               49.142857             130.019779   
809358                      0               30.000000              61.326992   
809359                     44               44.000000               0.000000   
809360                      0               30.500000              96.449469   

        ...  act_data_pkt_fwd  min_seg_size_forward  Active_Mean  \
0       ...               3.0                   0.0     739228.5   
1       ...               0.0                  32.0          0.0   
2       ...               3.0                  20.0          0.0   
3       ...               2.0                  20.0          0.0   
4       ...              11.0                  20.0          0.0   
...     ...               ...                   ...          ...   
809356  ...               6.0                   0.0     165265.0   
809357  ...               1.0                   0.0          0.0   
809358  ...               4.0                   0.0    1273143.0   
809359  ...               1.0                  20.0          0.0   
809360  ...               1.0                   0.0 

In [38]:
y = data.iloc[:,77]

In [39]:
y

0              DoS Hulk
1                BENIGN
2                BENIGN
3                BENIGN
4                BENIGN
              ...      
809356    DoS slowloris
809357         DoS Hulk
809358    DoS slowloris
809359           BENIGN
809360         DoS Hulk
Name: Label, Length: 809361, dtype: object

Standard Scaling and OnehotEncoding

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
cat_pipeline = Pipeline([
    ('select_cat', DataFrameSelector(["Label"])),
    ('cat_encoder', OneHotEncoder(sparse=False)),
])

In [19]:
from sklearn.base import BaseEstimator, TransformerMixin

class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names]

In [27]:
y=cat_pipeline.fit_transform(data)

In [28]:
y

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [43]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
sgd_clf = SGDClassifier(loss="log", penalty="l2")
sgd_clf.fit(X,Y)

SGDClassifier(loss='log')

In [44]:
from sklearn.model_selection import cross_val_score

sgd_scores = cross_val_score(sgd_clf, X, Y, cv=10)
sgd_scores.mean()

0.9962192404008576

In [45]:
sgd_scores

array([0.99558916, 0.99608333, 0.99521844, 0.99747949, 0.99602155,
       0.99725709, 0.99542849, 0.99562617, 0.99621923, 0.99726945])

Label_Encoder

In [40]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(y)
Y = label_encoder.transform(y)

In [41]:
Y

array([1, 0, 0, ..., 2, 0, 1])

# Using Decision Tree

In [46]:
from sklearn.tree import DecisionTreeClassifier
data

Destination_Port  Flow_Duration  Total_Fwd_Packets  \
0                     80      101168794                 20   
1                  60711             58                  1   
2                     53          31146                  4   
3                     80         254704                  3   
4                    443       11932077                 12   
...                  ...            ...                ...   
809356                80       68156881                 10   
809357                80         173608                  7   
809358                80       61923754                  7   
809359                53            744                  2   
809360                80         196947                 10   

        Total_Backward_Packets  Total_Length_of_Fwd_Packets  \
0                            1                          969   
1                            1                            0   
2                            2                          148   
3                            4                          429   
4                           16                         5030   
...                        ...                          ...   
809356                       1                          233   
809357                       1                          344   
809358                       1                          210   
809359                       2                           88   
809360                       1                          305   

        Total_Length_of_Bwd_Packets  Fwd_Packet_Length_Max  \
0                                 0                    353   
1                                 0                      0   
2                               244                     37   
3                               389                    423   
4                             15703                   1525   
...                             ...                    ...   
809356                            0                    168   
809357                            0                    344   
809358                            0                    168   
809359                          200                     44   
809360                            0                    305   

        Fwd_Packet_Length_Min  Fwd_Packet_Length_Mean  Fwd_Packet_Length_Std  \
0                           0               48.450000             119.083551   
1                           0                0.000000               0.000000   
2                          37               37.000000               0.000000   
3                           0              143.000000             242.505670   
4                           0              419.166667             644.896586   
...                       ...                     ...                    ...   
809356                      0               23.300000              51.337770   
809357                      0               49.142857             130.019779   
809358                      0               30.000000              61.326992   
809359                     44               44.000000               0.000000   
809360                      0               30.500000              96.449469   

        ...  min_seg_size_forward  Active_Mean    Active_Std  Active_Max  \
0       ...                   0.0     739228.5  7.431035e+05   1264682.0   
1       ...                  32.0          0.0  0.000000e+00         0.0   
2       ...                  20.0          0.0  0.000000e+00         0.0   
3       ...                  20.0          0.0  0.000000e+00         0.0   
4       ...                  20.0          0.0  0.000000e+00         0.0   
...     ...                   ...          ...           ...         ...   
809356  ...                   0.0     165265.0  1.529792e+05    306895.0   
809357  ...                   0.0          0.0  0.000000e+00         0.0   
809358  ...                   0.0    1273143.0  1.798484e+06   2544863.0   
809359  ...                  20.0       

In [47]:
X_train = data.iloc[:,:77]
y_train = data.iloc[:,77]

In [48]:
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [50]:
tree_scores = cross_val_score(tree_clf, X_train, y_train, cv=10)
tree_scores.mean()

0.9999579915299872

In [51]:
tree_scores

array([0.99997529, 0.99995058, 0.99991351, 0.99995058, 0.99997529,
       0.99995058, 0.99998764, 0.99995058, 0.99995058, 0.99997529])